Makefile
ci-values.yaml
pact-broker/requirements.lock
pact-broker/requirements.yaml
pact-broker/templates/deployment.yaml
pact-broker/templates/osba-db-instance.yaml
pact-broker/values.yaml

Postgresql PAAS is used and instantiated using OSBA
```
[ ] Yes
[x] No
```

Move to osba postgresql db.

---

azure-pipelines.yml

Increase timeouts for osba

---

azure-pipelines.yml

See: https://tools.hmcts.net/jira/browse/RPE-887
```
[ ] Yes
[x] No
```

Increase test install timeout

---

azure-pipelines.yml

Increase delete timeout

---

pact-broker/Chart.yaml
pact-broker/templates/osba-db-instance.yaml
pact-broker/values.yaml

Use general-purpose plan for osba db

---

azure-pipelines.yml
ci-values.yaml
pact-broker/Chart.yaml
pact-broker/requirements.yaml
pact-broker/templates/deployment.yaml
pact-broker/templates/osba-db-instance.yaml
pact-broker/values.yaml

Db can be osba, pod or external
```
[ ] Yes
[x] No
```

Db type selection

---

ci-values.yaml
pact-broker/Chart.yaml
pact-broker/templates/_helpers.tpl
pact-broker/templates/deployment.yaml
pact-broker/values.yaml

External db configuration
```
[ ] Yes
[x] No
```

Add external db config

---

pact-broker/Chart.yaml
pact-broker/templates/deployment.yaml

Quote defaults

---

pact-broker/Chart.yaml
pact-broker/templates/deployment.yaml

Single command

---

pact-broker/Chart.yaml
pact-broker/templates/deployment.yaml
pact-broker/values.yaml

Add servername to login

---

pact-broker/Chart.yaml
pact-broker/requirements.yaml

Upgrading postgresql chart

---

pact-broker/Chart.yaml
pact-broker/templates/_helpers.tpl
pact-broker/templates/deployment.yaml

clean up keyvaults

---

pact-broker/Chart.yaml
pact-broker/templates/deployment.yaml
pact-broker/values.yaml

Migrate to pactfoundation broker. Image as value

---

pact-broker/Chart.yaml
pact-broker/requirements.yaml
pact-broker/templates/deployment.yaml
pact-broker/templates/secretproviderclass.yaml

Moving chart to use csi volumes:

---

azure-pipelines.yml

[DTSPO-8339](https://tools.hmcts.net/jira/browse/DTSPO-8339)
```
[ ] Yes
[x] No
```

Parameterize ADO vmImage

---

pact-broker/Chart.yaml
pact-broker/templates/ingress.yaml

Update Ingress to networking.k8s.io/v1
```
[ ] Yes
[X] No
```

Update Ingress to networking.k8s.io/v1

---

pact-broker/Chart.yaml
pact-broker/templates/ingress.yaml
pact-broker/values.yaml

Add enableTls flag for traefik.ingress.kubernetes.io/router.tls
```
[ ] Yes
[X] No
```

Add enableTls flag for traefik.ingress.kubernetes.io/router.tls

---

pact-broker/templates/deployment.yaml
pact-broker/values.yaml

Flexible server doesn't use the @ suffix thing that single server did

DTSPO-11878 Pass through full username of DB

---

azure-pipelines.yml

Remediate notification 
``  | The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest)
`
```
[ ] Yes
[X] No
```

agent pool ubuntu-1804 to ubuntu-latest

---

pact-broker/templates/_helpers.tpl
pact-broker/templates/deployment.yaml
pact-broker/templates/secretproviderclass.yaml
pact-broker/values.yaml

DTSPO-12677
Update chart to support WI config
```
[ ] Yes
[ ] No
```

update chart with WI config

---

azure-pipelines.yml

Reverts hmcts/chart-pact-broker#50

Revert "DTSPO-22647 - Test devops library branch"
